# Generated by Django 5.2.6 on 2025-12-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentgateway_photographerpayout_platformcommission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='card_brand',
            field=models.CharField(blank=True, help_text='Visa, Mastercard, Amex, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='mobile_money_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='mobile_money_provider',
            field=models.CharField(blank=True, help_text='MTN, Airtel, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='paypal_payer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_brand',
            field=models.CharField(blank=True, help_text='Visa, Mastercard, Amex, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mobile_money_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mobile_money_provider',
            field=models.CharField(blank=True, help_text='MTN, Airtel, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paypal_payer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
