# Generated by Django 5.2.4 on 2025-09-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typical session price (optional)', max_digits=8, null=True),
        ),
    ]
