# Generated by Django 5.2.6 on 2025-09-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='awards',
            field=models.CharField(blank=True, help_text='Awards (comma-separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.CharField(blank=True, help_text='Badges or special recognitions (comma-separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.CharField(blank=True, help_text='Certifications (comma-separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='social_proof',
            field=models.URLField(blank=True, help_text='Link to social proof (portfolio, Instagram, etc.)'),
        ),
    ]
