# Generated by Django 5.2.6 on 2025-10-28 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, spaces, dots, hyphens, and underscores allowed.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain letters, numbers, spaces, dots, hyphens, and underscores.', regex='^[\\w\\s\\.\\-\\_]+$')], verbose_name='username'),
        ),
    ]
