# Generated by Django 5.2.6 on 2025-10-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('client', 'Client'), ('admin', 'Platform Admin')], default='client', max_length=20),
        ),
    ]
