# Generated by Django 5.2.6 on 2025-11-03 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_is_approved_contentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='CommunityPost',
        ),
    ]
