# Generated by Django 5.2.6 on 2025-09-16 13:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0002_userquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helparticle',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
