# Generated by Django 5.2.6 on 2025-10-30 10:33

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0003_alter_helparticle_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquestion',
            options={'ordering': ['-is_pinned', '-priority', '-submitted_at'], 'verbose_name': 'User Question', 'verbose_name_plural': 'User Questions'},
        ),
        migrations.AddField(
            model_name='userquestion',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admins (not sent to user)'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='admin_response',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Admin response to this question'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='faq_category',
            field=models.ForeignKey(blank=True, help_text='Category for FAQ organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpcenter.helpcategory'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='faq_title',
            field=models.CharField(blank=True, help_text='Title for FAQ display', max_length=200),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='is_faq',
            field=models.BooleanField(default=False, help_text='Mark as Frequently Asked Question'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin this question for admin visibility'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='responded_by',
            field=models.ForeignKey(blank=True, help_text='Admin who responded to this question', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Response'), ('responded', 'Responded'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
