# Generated by Django 5.2.6 on 2025-10-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='delivery_method',
            field=models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('both', 'Both In-App and Email')], default='in_app', max_length=10),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Custom email subject (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='emails_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='send_immediately',
            field=models.BooleanField(default=True, help_text='Send emails immediately or save as draft'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('feature', 'New Feature'), ('promotion', 'Promotion'), ('announcement', 'Announcement'), ('update', 'Update')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='target_users',
            field=models.CharField(choices=[('all', 'All Users'), ('photographers', 'Photographers Only'), ('clients', 'Clients Only'), ('admins', 'Admins Only'), ('verified', 'Verified Users Only'), ('unverified', 'Unverified Users Only')], default='all', max_length=20),
        ),
    ]
