# Generated by Django 5.2.6 on 2025-10-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending Analysis'), ('completed', 'Analysis Complete'), ('failed', 'Analysis Failed')], default='pending', max_length=20),
        ),
    ]
