# Generated by Django 5.2.6 on 2025-11-02 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_service_type'),
        ('reviews', '0005_reviewcategory_reviewhelpfulness_reviewresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anonymous_email',
            field=models.EmailField(blank=True, help_text='Optional email for anonymous reviews', max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='anonymous_name',
            field=models.CharField(blank=True, default='Anonymous', help_text='Name for anonymous reviews', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
