# Generated by Django 5.2.6 on 2025-11-02 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_anonymous_email_review_anonymous_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('anonymous_name', models.CharField(blank=True, max_length=100)),
                ('anonymous_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLikeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_dislikes', models.PositiveIntegerField(default=0)),
                ('total_helpful_votes', models.PositiveIntegerField(default=0)),
                ('total_not_helpful_votes', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='reviewhelpfulness',
            name='vote_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], default='helpful', max_length=15),
        ),
        migrations.AddIndex(
            model_name='reviewhelpfulness',
            index=models.Index(fields=['review', 'vote_type'], name='reviews_rev_review__47a9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpfulness',
            index=models.Index(fields=['user', 'created_at'], name='reviews_rev_user_id_2a3297_idx'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.reviewcomment'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewlikestats',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like_stats', to='reviews.review'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['review', 'created_at'], name='reviews_rev_review__b63a48_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['commenter', 'created_at'], name='reviews_rev_comment_306f46_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlikestats',
            index=models.Index(fields=['total_likes'], name='reviews_rev_total_l_e12fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlikestats',
            index=models.Index(fields=['total_dislikes'], name='reviews_rev_total_d_6691d1_idx'),
        ),
    ]
