# Complete Rwanda administrative locations data
# Structure: Province -> District -> Sector -> Cell -> Villages
# Generated from complete Dart data file (16,507 lines)

RWANDA_LOCATIONS = {
  "East": {
    "Bugesera": {},
    "Gashora": {},
    "Juru": {},
    "Kamabuye": {},
    "Mareba": {},
    "Mayange": {},
    "Musenyi": {},
    "Mwogo": {},
    "Ngeruka": {},
    "Ntarama": {},
    "Nyamata": {},
    "Nyarugenge": {},
    "Rilima": {},
    "Ruhuha": {},
    "Rweru": {},
    "Shyara": {},
    "Gatsibo": {},
    "Gasange": {},
    "Gitoki": {},
    "Kabarore": {},
    "Kageyo": {},
    "Kiramuruzi": {},
    "Kiziguro": {},
    "Muhura": {},
    "Murambi": {},
    "Ngarama": {},
    "Nyagihanga": {},
    "Remera": {},
    "Rugarama": {},
    "Rwimbogo": {},
    "Kayonza": {},
    "Gahini": {},
    "Kabare": {},
    "Kabarondo": {},
    "Mukarange": {},
    "Murama": {},
    "Murundi": {},
    "Mwiri": {},
    "Ndego": {},
    "Nyamirama": {},
    "Rukara": {},
    "Ruramira": {},
    "Rwinkwavu": {},
    "Kirehe": {},
    "Gahara": {},
    "Gatore": {},
    "Kigarama": {},
    "Kigina": {},
    "Mahama": {},
    "Mpanga": {},
    "Musaza": {},
    "Mushikiri": {},
    "Nasho": {},
    "Nyamugari": {},
    "Nyarubuye": {},
    "Ngoma": {},
    "Gashanda": {},
    "Jarama": {},
    "Karembo": {},
    "Kazo": {},
    "Kibungo": {},
    "Mugesera": {},
    "Mutenderi": {},
    "Rukira": {},
    "Rukumberi": {},
    "Rurenge": {},
    "Sake": {},
    "Zaza": {},
    "Nyagatare": {},
    "Gatunda": {},
    "Karama": {},
    "Karangazi": {},
    "Katabagemu": {},
    "Kiyombe": {},
    "Matimba": {},
    "Mimuri": {},
    "Mukama": {},
    "Musheri": {},
    "Rukomo": {},
    "Rwempasha": {},
    "Rwimiyaga": {},
    "Tabagwe": {},
    "Rwamagana": {},
    "Fumbwe": {},
    "Gahengeri": {},
    "Gishali": {},
    "Karenge": {},
    "Kigabiro": {},
    "Muhazi": {},
    "Munyaga": {},
    "Munyiginya": {},
    "Musha": {},
    "Muyumbu": {},
    "Mwulire": {},
    "Nyakaliro": {},
    "Nzige": {},
    "Rubona": {}
  },
  "Kigali": {
    "Gasabo": {},
    "Bumbogo": {},
    "Gatsata": {},
    "Gikomero": {},
    "Gisozi": {},
    "Jabana": {},
    "Jali": {},
    "Kacyiru": {},
    "Kimihurura": {},
    "Kimironko": {},
    "Kinyinya": {},
    "Ndera": {},
    "Nduba": {},
    "Remera": {},
    "Rusororo": {},
    "Rutunga": {},
    "Kicukiro": {},
    "Gahanga": {},
    "Gatenga": {},
    "Gikondo": {},
    "Kagarama": {},
    "Kanombe": {},
    "Kigarama": {},
    "Masaka": {},
    "Niboye": {},
    "Nyarugunga": {},
    "Nyarugenge": {},
    "Gitega": {},
    "Kanyinya": {},
    "Kigali": {},
    "Kimisagara": {},
    "Mageregere": {},
    "Muhima": {},
    "Nyakabanda": {},
    "Nyamirambo": {},
    "Rwezamenyo": {}
  },
  "North": {
    "Burera": {},
    "Bungwe": {},
    "Butaro": {},
    "Cyanika": {},
    "Cyeru": {},
    "Gahunga": {},
    "Gatebe": {},
    "Gitovu": {},
    "Kagogo": {},
    "Kinoni": {},
    "Kinyababa": {},
    "Kivuye": {},
    "Nemba": {},
    "Rugarama": {},
    "Rugengabari": {},
    "Ruhunde": {},
    "Rusarabuye": {},
    "Rwerere": {},
    "Gakenke": {},
    "Busengo": {},
    "Coko": {},
    "Cyabingo": {},
    "Gashenyi": {},
    "Janja": {},
    "Kamubuga": {},
    "Karambo": {},
    "Kivuruga": {},
    "Mataba": {},
    "Minazi": {},
    "Mugunga": {},
    "Muhondo": {},
    "Muyongwe": {},
    "Muzo": {},
    "Ruli": {},
    "Rusasa": {},
    "Rushashi": {},
    "Gicumbi": {},
    "Bukure": {},
    "Bwisige": {},
    "Byumba": {},
    "Cyumba": {},
    "Giti": {},
    "Kageyo": {},
    "Kaniga": {},
    "Manyagiro": {},
    "Miyove": {},
    "Mukarange": {},
    "Muko": {},
    "Mutete": {},
    "Nyamiyaga": {},
    "Nyankenke": {},
    "Rubaya": {},
    "Rukomo": {},
    "Rushaki": {},
    "Rutare": {},
    "Ruvune": {},
    "Rwamiko": {},
    "Shangasha": {},
    "Musanze": {},
    "Busogo": {},
    "Cyuve": {},
    "Gacaca": {},
    "Gashaki": {},
    "Gataraga": {},
    "Kimonyi": {},
    "Kinigi": {},
    "Muhoza": {},
    "Nkotsi": {},
    "Nyange": {},
    "Remera": {},
    "Rwaza": {},
    "Shingiro": {},
    "Rulindo": {},
    "Base": {},
    "Burega": {},
    "Bushoki": {},
    "Buyoga": {},
    "Cyinzuzi": {},
    "Cyungo": {},
    "Kinihira": {},
    "Kisaro": {},
    "Masoro": {},
    "Mbogo": {},
    "Murambi": {},
    "Ngoma": {},
    "Ntarabana": {},
    "Rukozo": {},
    "Rusiga": {},
    "Shyorongi": {},
    "Tumba": {}
  },
  "South": {
    "Gisagara": {},
    "Gikonko": {},
    "Gishubi": {},
    "Kansi": {},
    "Kibirizi": {},
    "Kigembe": {},
    "Mamba": {},
    "Muganza": {},
    "Mugombwa": {},
    "Mukindo": {},
    "Musha": {},
    "Ndora": {},
    "Nyanza": {},
    "Save": {},
    "Huye": {},
    "Gishamvu": {},
    "Karama": {},
    "Kigoma": {},
    "Kinazi": {},
    "Maraba": {},
    "Mbazi": {},
    "Mukura": {},
    "Ngoma": {},
    "Ruhashya": {},
    "Rusatira": {},
    "Rwaniro": {},
    "Simbi": {},
    "Tumba": {},
    "Kamonyi": {},
    "Gacurabwenge": {},
    "Kayenzi": {},
    "Kayumbu": {},
    "Mugina": {},
    "Musambira": {},
    "Ngamba": {},
    "Nyamiyaga": {},
    "Nyarubaka": {},
    "Rugarika": {},
    "Rukoma": {},
    "Runda": {},
    "Muhanga": {},
    "Cyeza": {},
    "Kabacuzi": {},
    "Kibangu": {},
    "Kiyumba": {},
    "Mushishiro": {},
    "Nyabinoni": {},
    "Nyamabuye": {},
    "Nyarusange": {},
    "Rongi": {},
    "Rugendabari": {},
    "Shyogwe": {},
    "Nyamagabe": {},
    "Buruhukiro": {},
    "Cyanika": {},
    "Gasaka": {},
    "Gatare": {},
    "Kaduha": {},
    "Kamegeri": {},
    "Kibumbwe": {},
    "Kitabi": {},
    "Mugano": {},
    "Musange": {},
    "Musebeya": {},
    "Mushubi": {},
    "Nkomane": {},
    "Tare": {},
    "Uwinkingi": {},
    "Busasamana": {},
    "Busoro": {},
    "Cyabakamyi": {},
    "Kibilizi": {},
    "Mukingo": {},
    "Muyira": {},
    "Ntyazo": {},
    "Nyagisozi": {},
    "Rwabicuma": {},
    "Nyaruguru": {},
    "Busanze": {},
    "Cyahinda": {},
    "Kibeho": {},
    "Kivu": {},
    "Mata": {},
    "Munini": {},
    "Ngera": {},
    "Nyabimata": {},
    "Ruheru": {},
    "Ruramba": {},
    "Rusenge": {},
    "Ruhango": {},
    "Bweramana": {},
    "Byimana": {},
    "Kabagali": {},
    "Kinihira": {},
    "Mbuye": {},
    "Mwendo": {},
    "Ntongwe": {}
  },
  "West": {
    "Karongi": {},
    "Bwishyura": {},
    "Gashari": {},
    "Gishyita": {},
    "Gitesi": {},
    "Mubuga": {},
    "Murambi": {},
    "Murundi": {},
    "Mutuntu": {},
    "Rubengera": {},
    "Rugabano": {},
    "Ruganda": {},
    "Rwankuba": {},
    "Twumba": {},
    "Ngororero": {},
    "Bwira": {},
    "Gatumba": {},
    "Hindiro": {},
    "Kabaya": {},
    "Kageyo": {},
    "Kavumu": {},
    "Matyazo": {},
    "Muhanda": {},
    "Muhororo": {},
    "Ndaro": {},
    "Nyange": {},
    "Sovu": {},
    "Nyabihu": {},
    "Bigogwe": {},
    "Jenda": {},
    "Jomba": {},
    "Kabatwa": {},
    "Karago": {},
    "Kintobo": {},
    "Mukamira": {},
    "Muringa": {},
    "Rambura": {},
    "Rugera": {},
    "Rurembo": {},
    "Shyira": {},
    "Nyamasheke": {},
    "Bushekeri": {},
    "Bushenge": {},
    "Cyato": {},
    "Gihombo": {},
    "Kagano": {},
    "Kanjongo": {},
    "Karambi": {},
    "Karengera": {},
    "Kirimbi": {},
    "Macuba": {},
    "Mahembe": {},
    "Nyabitekeri": {},
    "Rangiro": {},
    "Ruharambuga": {},
    "Shangi": {},
    "Rubavu": {},
    "Bugeshi": {},
    "Busasamana": {},
    "Cyanzarwe": {},
    "Gisenyi": {},
    "Kanama": {},
    "Kanzenze": {},
    "Mudende": {},
    "Nyakiriba": {},
    "Nyamyumba": {},
    "Nyundo": {},
    "Rugerero": {},
    "Rutsiro": {},
    "Boneza": {},
    "Gihango": {},
    "Kigeyo": {},
    "Kivumu": {},
    "Manihira": {},
    "Mukura": {},
    "Murunda": {},
    "Musasa": {},
    "Mushonyi": {},
    "Mushubati": {},
    "Nyabirasi": {},
    "Ruhango": {},
    "Rusebeya": {},
    "Rusizi": {},
    "Bugarama": {},
    "Butare": {},
    "Bweyeye": {},
    "Gashonga": {},
    "Giheke": {},
    "Gihundwe": {},
    "Gikundamvura": {},
    "Gitambi": {},
    "Kamembe": {},
    "Muganza": {},
    "Mururu": {},
    "Nkanka": {},
    "Nkombo": {},
    "Nkungu": {},
    "Nyakabuye": {},
    "Nyakarenzo": {},
    "Nzahaha": {},
    "Rwimbogo": {}
  }
}

def get_provinces():
    """Get list of all provinces"""
    return list(RWANDA_LOCATIONS.keys())

def get_districts(province):
    """Get list of districts in a province"""
    if province in RWANDA_LOCATIONS:
        return list(RWANDA_LOCATIONS[province].keys())
    return []

def get_sectors(province, district):
    """Get list of sectors in a district"""
    if province in RWANDA_LOCATIONS and district in RWANDA_LOCATIONS[province]:
        return list(RWANDA_LOCATIONS[province][district].keys())
    return []

def get_cells(province, district, sector):
    """Get list of cells in a sector"""
    if (province in RWANDA_LOCATIONS and 
        district in RWANDA_LOCATIONS[province] and 
        sector in RWANDA_LOCATIONS[province][district]):
        return list(RWANDA_LOCATIONS[province][district][sector].keys())
    return []

def get_villages(province, district, sector, cell):
    """Get list of villages in a cell"""
    if (province in RWANDA_LOCATIONS and 
        district in RWANDA_LOCATIONS[province] and 
        sector in RWANDA_LOCATIONS[province][district] and
        cell in RWANDA_LOCATIONS[province][district][sector]):
        return RWANDA_LOCATIONS[province][district][sector][cell]
    return []

def format_location(province=None, district=None, sector=None, cell=None, village=None):
    """Format location components into a readable string"""
    components = []
    if village:
        components.append(village)
    if cell:
        components.append(cell)
    if sector:
        components.append(sector)
    if district:
        components.append(district)
    if province:
        components.append(province)
    
    return ", ".join(components) if components else ""

def get_location_stats():
    """Get statistics about the location data"""
    stats = {
        'provinces': len(RWANDA_LOCATIONS),
        'districts': 0,
        'sectors': 0,
        'cells': 0,
        'villages': 0
    }
    
    for province, districts in RWANDA_LOCATIONS.items():
        stats['districts'] += len(districts)
        for district, sectors in districts.items():
            stats['sectors'] += len(sectors)
            for sector, cells in sectors.items():
                stats['cells'] += len(cells)
                for cell, villages in cells.items():
                    stats['villages'] += len(villages)
    
    return stats

# Print statistics when imported
if __name__ == "__main__":
    stats = get_location_stats()
    print("Rwanda Locations Database Statistics:")
    print(f"Provinces: {stats['provinces']}")
    print(f"Districts: {stats['districts']}")
    print(f"Sectors: {stats['sectors']}")
    print(f"Cells: {stats['cells']}")
    print(f"Villages: {stats['villages']}")
