# Generated by Django 5.2.4 on 2025-09-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve before public display.'),
        ),
    ]
