# Generated by Django 5.2.6 on 2025-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_photolike_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
