# Generated by Django 5.2.6 on 2025-09-16 13:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_privacypolicy_termsofservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
