# Generated by Django 5.2.6 on 2025-11-02 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_privacypolicy_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='photocomment',
            name='anonymous_email',
            field=models.EmailField(blank=True, help_text='Optional email for anonymous users', max_length=254),
        ),
        migrations.AddField(
            model_name='photocomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portfolio.photocomment'),
        ),
    ]
