# Generated by Django 5.2.6 on 2025-10-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('wedding', '💍 Wedding Photography'), ('engagement', '💕 Engagement Session'), ('portrait', '👨\u200d👩\u200d👧\u200d👦 Family Portrait'), ('maternity', '🤰 Maternity Photography'), ('newborn', '👶 Newborn Photography'), ('children', '🧒 Children Photography'), ('headshots', '💼 Professional Headshots'), ('corporate', '🏢 Corporate Events'), ('business', '💼 Business Photography'), ('conference', '🎤 Conference Photography'), ('product', '📦 Product Photography'), ('commercial', '🏭 Commercial Photography'), ('real_estate', '🏠 Real Estate Photography'), ('food', '🍽️ Food Photography'), ('fashion', '👗 Fashion Photography'), ('lifestyle', '✨ Lifestyle Photography'), ('travel', '✈️ Travel Photography'), ('landscape', '🏔️ Landscape Photography'), ('nature', '🌿 Nature Photography'), ('wildlife', '🦁 Wildlife Photography'), ('sports', '⚽ Sports Photography'), ('event', '🎉 Event Photography'), ('party', '🎈 Party Photography'), ('birthday', '🎂 Birthday Photography'), ('graduation', '🎓 Graduation Photography'), ('anniversary', '💏 Anniversary Photography'), ('reunion', '👥 Family Reunion'), ('cultural', '🎭 Cultural Events'), ('religious', '⛪ Religious Ceremonies'), ('artistic', '🎨 Artistic Photography'), ('documentary', '📷 Documentary Photography'), ('street', '🛣️ Street Photography'), ('architecture', '🏛️ Architecture Photography'), ('automotive', '🚗 Automotive Photography'), ('aerial', '🚁 Aerial/Drone Photography'), ('underwater', '🤿 Underwater Photography'), ('macro', '🔍 Macro Photography'), ('black_white', '⚫ Black & White Photography'), ('vintage', '📸 Vintage Style Photography'), ('custom', '🎯 Custom Photography Session')], max_length=100),
        ),
    ]
